name: Continuous deployment (NPM)

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

jobs:
  build-and-deploy:
    name: Build and deploy NPM package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: '1'

      - name: Configure node for npmjs.org as registry
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Post build
        run: npm run postbuild

      - name: Publish package on npmjs.org
        run: npm publish ./storybook-static --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
