name: Release please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: Handle releases
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: react-alternating-timeline
    outputs:
      ref: refs/tags/${{ steps.release.outputs.tag_name }}
      released: ${{ steps.release.outputs.releases_created }}

  deploy-to-npm:
    name: Deploy to NPM
    uses: ./.github/workflows/cd-npm.yml
    needs: release-please
    with:
      ref: refs/tags/${{ needs.release-please.outputs.ref }}
    if: ${{ needs.release-please.outputs.released }}
